### ISSUE TITLE
Unhandled exception on launch

### ISSUE THREAD

**Issue by jabroni181** [Winterstark/Wallcreeper#2]
An error message comes up when trying to run the program (Windows 7 with Net Framework 4.5 Installed). It keeps coming up even if I click continue. 

![image](https://cloud.githubusercontent.com/assets/13949874/9448881/249045e4-4a6d-11e5-9532-5069ff7396c5.png)

This is the full text from the error details: 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s)
   at Wallcreeper.formMain.checkDate(String date)
   at Wallcreeper.formMain.isValidNow(Theme theme)
   at Wallcreeper.formMain.worker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18444 built by: FX451RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Wallcreeper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/Cal/Documents/Wallcreeper/Wallcreeper.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

GenericForms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/Cal/Documents/Wallcreeper/GenericForms.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Winterstark** [comment]
Hi, thanks for the detailed report!

I think I know what the problem is: the program has many wallpaper themes set up by default, and a few of them have a specific date when they are active, for example New Year: 31.12. Everything works great as long as your Windows uses the same DateTime format, but I assume you're from North America where the month and day are reversed, so then the program can't convert the string to a DateTime object.

I'll probably make a new Wallcreeper version with the fix tomorrow, but until then you can download [an edited version of themes.txt without any specific dates](https://raw.githubusercontent.com/Winterstark/Wallcreeper/master/themes.txt). Replace the old themes.txt with this version and the problem should hopefully go away.

**Comment by ABJ-SH** [comment]
The edited themes.txt works until you create a theme with...specific dates in it.
